[package]
name = "zed_v"
version = "0.5.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/v.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "<1"

[profile.release]
lto = "thin"
